version: "3.6"

services:

  elasticsearch:
    image: elasticsearch:7.5.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elastic:/usr/share/elasticsearch/data

  logstash:
    image: logstash:7.5.1
    command: bin/logstash -f /etc/logstash/conf.d/logstash.conf
    depends_on:
      - elasticsearch
    links:
      - "elasticsearch:elastic.container"
    expose:
      - "12201/udp"

  kibana:
    image: kibana:7.5.1
    depends_on:
      - elasticsearch
    links:
      - "elasticsearch:elastic.container"
    ports:
      - "5601:5601"

  parser:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - logstash


volumes:
  elastic: {}
